"""Add url column to tournaments

Revision ID: 82c3ae35e0e3
Revises: 8ad9071ea833
Create Date: 2025-08-27 20:10:24.174745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c3ae35e0e3'
down_revision: Union[str, Sequence[str], None] = '8ad9071ea833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'url')
    # ### end Alembic commands ###
